### ISSUE TITLE
Release photon 0.3.1

### ISSUE THREAD

**Issue by JsLth** [JsLth/photon#1]
First release:

* [x] `usethis::use_news_md()`
* [x] `usethis::use_cran_comments()`
* [x] Update (aspirational) install instructions in README
* [x] Proofread `Title:` and `Description:`
* [x] Check that all exported functions have `@return` and `@examples`
* [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
* [x] Check [licensing of included files](https://r-pkgs.org/license.html#sec-code-you-bundle)
* [x] Review <https://github.com/DavisVaughan/extrachecks>

Prepare for release:

* [x] `git pull`
* [x] `usethis::use_github_links()`
* [x] `urlchecker::url_check()`
* [x] `devtools::build_readme()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `git push`

Submit to CRAN:

* [x] `usethis::use_version('patch')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version(push = TRUE)`
* [x] `usethis::use_news_md()`

**Comment by e-kotov** [comment]
@JsLth congrats on the CRAN release. I was going to suggest you my [`{rJavaEnv}`](https://github.com/e-kotov/rJavaEnv) package, but I noticed that it is already in your codebase as a suggestion. Thanks)

**Comment by JsLth** [comment]
Hi @e-kotov, thanks for the congrats! Just to be sure, is there any specific way you would like `{rJavaEnv}` to be suggested or used by packages? I'm thinking of adding a similar suggestion to the [`{rors}`](https://github.com/JsLth/rors) package and it would be good to know if there are any standards or good practices before really committing to a routine. 😄

**Comment by e-kotov** [comment]
@JsLth I think your way of suggesting is good, as the user will see it even if they don't read the docs or the vignettes. But another good way to suggest is simply in the readme and/or package vignettes. E.g. here it is suggested in the readme https://github.com/ipeaGIT/r5r/ and will eventually make it's way to the package website when Raphael re-renders it. Also, Raphael includes rJavaEnv into workshop tutorials like here https://ipeagit.github.io/access_workshop_bogota_2024/2.1_installation.html#installing-java
